### ISSUE TITLE
What CC1101 device to use ?

### ISSUE THREAD

**Issue by pierok13** [stanleypa/eleropy#2]
Hi,
I've high interest in your work and I think it's a great work.
What CC1101 device did you use ?
Would this one be a good catch ?
https://www.amazon.fr/gp/product/B07YX92NMP/
thank's

**Comment by stanleypa** [comment]
The modules i used looked like this:

But I'm pretty sure the one you linked would work.

**Comment by stanleypa** [comment]
Sorry Image file didn't work

https://www.aliexpress.com/item/4001159064538.html?spm=a2g0o.productlist.main.25.208538b3iKuE1p&algo_pvid=3de533c2-65d9-4a11-8598-cef2447d820c&algo_exp_id=3de533c2-65d9-4a11-8598-cef2447d820c-12&pdp_npi=3%40dis%21EUR%212.33%211.89%21%21%212.48%21%21%40212243c016885521261167853d0784%2110000014938416272%21sea%21IE%21143095164&curPageLogUid=WkP6pbeNSiGf

**Comment by pierok13** [comment]
The one I saw looks like it's only 433 MHZ and I think elero needs 868 right ?

**Comment by stanleypa** [comment]
There's 868, 433 and 915mhz versions - i believe only difference is the
passive component values.

**Comment by pierok13** [comment]
Thank's for your reply, I'll try the same than yours, I don't want to risk and have to order a new one.

**Comment by pierok13** [comment]
@stanleypa I have the CC1101 and the remotes , installed on RPI spiDEV 0
The scripts shows only dots, waiting ofr clear channel.
My question is how to sniff to identify the remotes and fill the conf.py ?
I'm sorry, I'm new in the CC1101 world.

**Comment by stanleypa** [comment]
At startup you should see something like:

Starting main.py
check 114
Waiting for clear channel...
........channel cleared

The "check" is a read of the a register just written (0x0E - the middle byte of the frequency). What is the value? If this is 0 then the SPI bus is not okay (probably should abort) in which case I'd suggest you make sure you have enabled SPI on the PI and double-check your wiring to the module.
