### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by lomion0815** [stanleypa/eleropy#3]
Can you please apply an open source license to your code. I would like to provide improvements for esp8266 based systems (like nodeMCU).
Thank you for your great work!

**Comment by stanleypa** [comment]
done

**Comment by lomion0815** [comment]
Thank you very much!
Just a remark: According to https://www.gnu.org/licenses/gpl-howto.html you would need to add a license and copyright notice to every source file but I am fine this way ;-)
